# Generated by Django 5.0.3 on 2026-04-15 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Patient's full name", max_length=200)),
                ('phone_number', models.CharField(help_text='Primary contact number for AI calls and SMS', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(help_text="Patient's date of birth")),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text="Patient's gender", max_length=10)),
                ('email', models.EmailField(blank=True, help_text='Email for appointment reminders', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text="Patient's address", null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Medical history, reason for visit, prior notes', null=True)),
                ('referring_doctor', models.CharField(blank=True, help_text='Name of referring physician', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
