# Generated by Django 5.0.3 on 2026-05-31 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("patients", "0004_make_assigned_doctor_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="assigned_doctor",
            field=models.ForeignKey(
                help_text="Primary doctor assigned to this patient (Required)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_patients",
                to="doctors.doctor",
                verbose_name="Assigned doctor *",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                help_text="Patient's date of birth", verbose_name="Date of birth *"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="full_name",
            field=models.CharField(
                help_text="Patient's full name",
                max_length=200,
                verbose_name="Full name *",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                help_text="Patient's gender",
                max_length=10,
                verbose_name="Gender *",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                help_text="Primary contact number for AI calls and SMS",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone number *",
            ),
        ),
    ]
