# Generated by Django 5.0.3 on 2026-04-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_patient_assigned_doctor"),
        ("scheduling", "0002_add_pending_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_CONFIRMATION", "Appointment Confirmation"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("GENERAL", "General Message"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                ("message_body", models.TextField(help_text="SMS message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("twilio_sid", models.CharField(blank=True, max_length=100, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "sms_logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
