# Generated by Django 5.0.3 on 2026-04-15 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Doctor's full name", max_length=200)),
                ('specialization', models.CharField(help_text='Medical specialization (e.g., Radiology, Pathology)', max_length=200)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Active doctors appear in scheduling', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(help_text='Date of the slot')),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes')], default=30, help_text='Slot duration in minutes')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Slot availability status', max_length=10)),
                ('booked_at', models.DateTimeField(blank=True, help_text='Timestamp when slot was booked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Slot',
                'verbose_name_plural': 'Doctor Slots',
                'db_table': 'doctor_slots',
                'ordering': ['slot_date', 'start_time'],
            },
        ),
    ]
