# Generated by Django 5.0.3 on 2026-04-15 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for doctor login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='booked_patient',
            field=models.ForeignKey(blank=True, help_text='Patient who booked this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor for this slot', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status'], name='doctors_status_f1630d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['doctor', 'slot_date', 'status'], name='doctor_slot_doctor__6e4efa_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['slot_date', 'status'], name='doctor_slot_slot_da_fff4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['booked_patient'], name='doctor_slot_booked__782825_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together={('doctor', 'slot_date', 'start_time')},
        ),
    ]
