# Generated by Django 5.0.3 on 2026-04-15 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', help_text='Appointment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Appointment notes or reason for visit', null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True, help_text='When the appointment was booked')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(help_text='Staff member who booked this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('slot', models.OneToOneField(help_text='Doctor slot for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctors.doctorslot')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['patient', '-booked_at'], name='appointment_patient_854a17_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['-booked_at'], name='appointment_booked__412dab_idx')],
            },
        ),
    ]
