# Generated by Django 5.0.3 on 2026-04-16 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                            ("REMINDER_24H", "24-Hour Reminder"),
                            ("REMINDER_1H", "1-Hour Reminder"),
                            ("CANCELLATION", "Cancellation"),
                            ("RESCHEDULING", "Rescheduling"),
                        ],
                        default="REMINDER_24H",
                        help_text="Type of reminder",
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("BOTH", "Both")],
                        default="SMS",
                        help_text="Delivery channel",
                        max_length=10,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(help_text="Message content sent to patient"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the reminder was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reminder was delivered",
                        null=True,
                    ),
                ),
                (
                    "twilio_message_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio message SID (for SMS)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Email service message ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "last_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last retry was attempted",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if delivery failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reminder was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the reminder was last updated"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        help_text="Appointment for this reminder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient receiving the reminder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Log",
                "verbose_name_plural": "Reminder Logs",
                "db_table": "reminder_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["appointment", "-created_at"],
                        name="reminder_lo_appoint_ca1244_idx",
                    ),
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="reminder_lo_patient_5de29c_idx",
                    ),
                    models.Index(
                        fields=["delivery_status"],
                        name="reminder_lo_deliver_d3d48b_idx",
                    ),
                    models.Index(
                        fields=["reminder_type"], name="reminder_lo_reminde_c95949_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="reminder_lo_created_350abe_idx"
                    ),
                ],
            },
        ),
    ]
