# Generated by Django 5.0.3 on 2026-04-16 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("SLOT_OFFER", "Slot Offer"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Type of call",
                        max_length=30,
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1, help_text="Attempt number (1, 2, or 3)"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ANSWERED", "Answered"),
                            ("NO_ANSWER", "No Answer"),
                            ("BUSY", "Busy"),
                            ("FAILED", "Failed"),
                            ("VOICEMAIL", "Voicemail"),
                            ("COMPLETED", "Completed"),
                        ],
                        help_text="Call outcome",
                        max_length=20,
                    ),
                ),
                (
                    "twilio_call_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio call SID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "twilio_recording_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to call recording",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Call duration in seconds", null=True
                    ),
                ),
                (
                    "transcription_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("NO_RECORDING", "No Recording"),
                        ],
                        default="NO_RECORDING",
                        help_text="Transcription status",
                        max_length=20,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the call was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the call completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the call",
                        null=True,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related appointment (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient who was called",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "db_table": "call_logs",
                "ordering": ["-initiated_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-initiated_at"],
                        name="call_logs_patient_b8cce6_idx",
                    ),
                    models.Index(
                        fields=["appointment"], name="call_logs_appoint_d7ad05_idx"
                    ),
                    models.Index(
                        fields=["outcome"], name="call_logs_outcome_f6150c_idx"
                    ),
                    models.Index(
                        fields=["transcription_status"],
                        name="call_logs_transcr_692035_idx",
                    ),
                    models.Index(
                        fields=["-initiated_at"], name="call_logs_initiat_f6affd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManualCallbackTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for manual callback (e.g., '3 AI call attempts failed')"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for staff", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was created"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task was completed", null=True
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related appointment (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_callback_tasks",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_callback_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who completed this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_callback_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient to call back",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_callback_tasks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Callback Task",
                "verbose_name_plural": "Manual Callback Tasks",
                "db_table": "manual_callback_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="manual_call_patient_c7dceb_idx",
                    ),
                    models.Index(
                        fields=["status"], name="manual_call_status_fec289_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="manual_call_assigne_307656_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="manual_call_created_86534f_idx"
                    ),
                ],
            },
        ),
    ]
