# Generated by Django 5.0.3 on 2026-04-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                    ("APPOINTMENT_CONFIRMATION", "Appointment Confirmation"),
                    ("SLOT_OFFER", "Slot Offer"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                help_text="Type of call",
                max_length=30,
            ),
        ),
    ]
