# Generated by Django 5.0.3 on 2026-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calling", "0002_alter_calllog_call_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANSWERED", "Answered"),
                    ("NO_ANSWER", "No Answer"),
                    ("BUSY", "Busy"),
                    ("FAILED", "Failed"),
                    ("VOICEMAIL", "Voicemail"),
                    ("COMPLETED", "Completed"),
                ],
                help_text="Call outcome",
                max_length=20,
                null=True,
            ),
        ),
    ]
