# Generated by Django 5.0.3 on 2026-04-16 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calling", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Transcribed text from call recording"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Transcription status",
                        max_length=20,
                    ),
                ),
                (
                    "whisper_model",
                    models.CharField(
                        default="whisper-1",
                        help_text="Whisper model used for transcription",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Transcription confidence score (if available)",
                        null=True,
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether transcription has been edited by staff",
                    ),
                ),
                (
                    "last_edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the transcription was last edited",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the transcription was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the transcription was last updated",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related appointment (auto-tagged)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcriptions",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "call_log",
                    models.OneToOneField(
                        help_text="Call log for this transcription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription",
                        to="calling.calllog",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who last edited this transcription",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_transcriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcription",
                "verbose_name_plural": "Transcriptions",
                "db_table": "transcriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["call_log"], name="transcripti_call_lo_a1dcbf_idx"
                    ),
                    models.Index(
                        fields=["appointment"], name="transcripti_appoint_4a356c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="transcripti_status_b599b6_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="transcripti_created_407c6c_idx"
                    ),
                ],
            },
        ),
    ]
